
version: "3.0"
services: 
  servicemain:
    build: /backend/main/
    command: uvicorn main:app --host 0.0.0.0 --port 80
    container_name: main 
    ports:
      - "80:80"
    networks:
        - app-network
   
    
  servicegenerator:
    build: /backend/namesgenerator/
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    container_name: generator
    ports:
      - "8080:8080"
    networks:
        - app-network


  passwordgenerator:
    build: /backend/password/
    command: uvicorn main:app --host 0.0.0.0 --port 50
    container_name: password
    ports:
       - "50:50"
    networks:
         - app-network


        

  react:
    build: /frontend/
    ports:
      - "3000:3000"
    networks:
      - app-network
    container_name: react
    stdin_open: true  
    volumes:
      - /frontend/src/app  
      - /frontend/src/node_modules
    
    
networks:
  app-network:
    driver: bridge 